export interface Challan{
    challanID: number | 0,
    challanName: string | null,
    monthYear: string | null,
    challanType: string | null,
    transactionDate: string | null,
    totalEmployee: number | 0,
    paidDays: number | 0,
    pfGross: number | 0,
    pf: number | 0,
    epfAcc1: number | 0,
    epsAcc10: number | 0,
    pfAdminChargesAcc2: number | 0,
    edliAcc21: number | 0,
    edliAdminChargesAcc22: number | 0,
    epsGross: number | 0,
    edliGross: number | 0,
    form5Employee: number | 0,
    form10Employee: number | 0,
    showHoldPF: true,
    showZeroPF: true,
    epsEmployee: number | 0,
    branchCode: string | null,
    esiGross: number | 0,
    esi: number | 0,
    esiEmployer: number | 0,
    lwfGross: number | 0,
    lwf: number | 0,
    lwfEmployer: number | 0,
    ptGross: number | 0,
    pt: number | 0,
    submittedDate: string | null,
    acknowledgementNumber: string | null,
    paymentModeID: number | 0,
    chequeNo: string | null,
    submittedByDetail: string | null,
    submittedBy: number | 0,
    reciptFilePath: string | null,
    reciptFilePathURL: string | null,
    chanllanFileName: string | null,
    remark: string | null,
}