export interface EmployeeSeparation{
    employeeID: number | 0,
    employeeCode: string |null,
    employeeName: string | null,
    company: string | null,
    department: string | null,
    designation: string | null,
    branch: string | null,
    displayName: string | null,
    employeeStatusID: number | 0,
    employeeStatusName: string,
    joiningDate:string |null,
    leavingDate: string |null,
    resignationDate: string |null,
    employeeSettlementRequestID: number | 0,
    employeeLeavingDetailID: number | 0
}

export interface EmployeeSeparationDetail{
    employeeID: number | 0,
    employeeCode: string |null,
    employeeName: string | null,
    company: string | null,
    department: string | null,
    designation: string | null,
    branch: string | null,
    displayName: string | null,
    employeeStatusID: number | 0,
    employeeStatusName: string,
    joiningDate:string |null,
    leavingDate: string |null,
    resignationDate: string |null,
    employeeSettlementRequestID: number | 0,
    employeeLeavingDetailID: number | 0,
    noticePeriod: number | 0,
    noticePeriodType: string | null,
    noticePayType: string | null,
    employeeLastStatusID: number | 0,
    separationRemark: string | null,
    remark: string | null
}

export interface EmployeeSettlementDetail{
    employeeSettlementRequestID: number | 0,
    employeeID: number | 0,
    paid: boolean | true,
    paidDate: string |null,
    paymentModeID: number | 0,
    paymentBankID: number | 0,
    bankName: string |null,
    branchName: string |null,
    ifscCode: string |null,
    bankAccountNo: string |null,
    chequeNumber: string |null,
    chequeDate: string |null,
    paidRemarks: string |null,
    displayName: string |null,
    settlementRemark: string |null,
    settlementReasonID: number | 0,
    loanRecovery: number | 0,
    assetRecovery: number | 0,
    adjustDays: number | 0,
    employeeStatusID: number | 0,
    employeeStatusName: string |null,
    joiningDate: string |null,
    leavingDate: string |null,
    resignationDate: string |null,
    employeeLeavingDetailID: number | 0,
    noticePeriod: number | 0,
    noticePeriodType: string |null,
    noticePayType: string |null,
    employeeLastStatusID: number | 0,
    separationRemark: string |null,
    settlementMonthYear: string |null,
    settlementDate: string |null,
    noticeAmount: number | 0,
    settlementReason: string |null,
    leaveCount: number | 0,
    leaveAmount: number | 0,
    gratuityAmount: number | 0,
    bonusAmount: number | 0,
    actualPaidDays: number | 0,
    paidDays: number | 0,
    netPay: number | 0,
    otherDeductionAmount: number | 0,
    otherAdditionAmount: number | 0,
    salaryAmount: number | 0,
    holdSalaryAmount: number | 0
}