export interface Employee {
      employeeID: number,
      employeeCode: string | null ,
      punchID: string | null ,
      employeeStatusID: number,
      employeeTypeID: number,
      employeeName: string | null ,
      joiningDate: string | null ,
      organizationID: number,
      companyID: number,
      branchID: number,
      contractorID: number,
      departmentID: number,
      subDepartmentID: number,
      designationID: number,
      sectionID: number,
      categoryID: number,
      gradeID: number,
      levelID: number,
      probationPeriod: number,
      probationPeriodType: string | null ,
      confirmationDate: string | null ,
      dateOfBirth: string | null ,
      retirementYear: number,
      retirementDate: string | null ,
      leavingDate: string | null ,
      leavingReason: string | null ,
      resignationDate: string | null ,
      fatherName: string | null ,
      motherName: string | null ,
      guardianName: string | null ,
      spouseName: string | null ,
      marriageDate: string | null ,
      maritalStatusID: number,
      aadharNumber: string | null ,
      panNo: string | null ,
      uanNumber: string | null ,
      pfNumber: string | null ,
      esiNumber: string | null ,
      paymentModeID:number,
      paymentBankID:number
      bankName: string | null ,
      branchName: string | null ,
      bankAccountNo: string | null ,
      ifscCode: string | null ,
      mobileNo: string | null ,
      dispensaryID: number,
      emailID: string | null ,
      genderID: number,
      bloodGroupID: number,
      currentAddress: string | null ,
      currentCountryID: number,
      currentStateID: number,
      currentCityID: number,
      currentZip: number,
      permanentAddress: string | null ,
      permanentCountryID: number,
      permanentStateID: number,
      permanentCityID: number,
      permanentZip: number,
      emergencyContectPerson: string | null ,
      contactNumberEmergency: string | null ,
      emergencyContectRelationshipID: number,
      employeeSkillTypeID: number,
      vehicalDetail: string | null ,
      vehicalNo: string | null ,
      religionID: number,
      nationalityID: number,
      blacklisted: boolean,
      blacklistReason: string | null ,
      blacklistBy: number,
      blacklistDate: string | null ,
      domicile: string | null ,
      bondYear: string | null ,
      profileImagePath: string | null ,
      signatureImagePath: string | null ,
      noticePeriod: number,
      noticePeriodType: string | null ,
      profileImagePathID:string | null ,
      signatureImagePathID :string | null,
      reportingManagerID: number | 0,
      reportingManager: string| null,
      functionalManagerID: number |0,
      functionalManager: string | null,
      userLogin: boolean | false,
      mobileLogin: boolean | false,
      allowDevicePunch: boolean | false,
      snrNumber: string | null,
      deviceAccessValidUpto : string | null,
      employeePunchTypeID : number | 0

  }

  export interface EmployeeMaster{
    key: string | null,
    value: number
  }
export interface EmployeeProfile{
  employeeID: number,
  employeeCode: string | null,
  punchID: string | null,
  employeeName: string | null,
  joiningDate: string | null,
  dateOfBirth: string | null,
  leavingDate: string | null,
  leavingReason: string | null,
  resignedDate: string | null ,
  profileImagePath: string | null,
  signatureImagePath: string | null,
  maritalStatus: string | null,
  emailID: string | null,
  gender: string | null,
  mobileNo: string | null,
  organization: string | null,
  company: string | null,
  branch: string | null,
  contractor: string | null,
  category: string | null,
  department: string | null,
  subDepartment: string | null,
  designation: string | null,
  level: string | null,
  section: string | null,
  grade: string | null,
  employeeType: string | null,
  employeeStatus: string | null,
  organizationCode: string | null,
  companyCode: string | null,
  branchCode: string | null,
  contractorCode: string | null,
  categoryCode: string | null,
  departmentCode: string | null,
  subDepartmentCode: string | null,
  designationCode: string | null,
  levelCode: string | null,
  sectionCode: string | null,
  gradeCode: string | null,
  reportingManagerCode: string | null,
  reportingManagerName: string | null,
  functionalManagerCode: string | null,
  functionalManagerName: string | null,
  pfNumber: string | null,
  esiNumber: string | null,
  uanNumber: string | null,
  panNo: string | null,
  aadharNumber: string | null,
  bankName: string | null,
  branchName: string | null,
  bankAccountNo: string | null,
  ifscCode: string | null,
  passwordChangeRequired: boolean,
  reLogin: boolean,
  mobileLogin: boolean,
  active: boolean
}
