export interface MachineMaster {
     machineID : number | 0,
     machineCode: string | "",
     machineName: string | "",
     branchID: number|0,
     machineModelID: number | 0,
     machineTypeID: number | 0,
     clientMode: boolean | false,
     ipAddress: string | "",
     subnetmask: string | "",
     gateway: string | "",
     port: string | "",
     macAddress: string | "",
     dnsServer: string |"",
     registerd: boolean | false,
     connectivityType: string | "",
     connectivityInterval: number | 0,
     lastDownloadFlag: string | "",
     hold: boolean | false,
     adminPassoword: string |"",
     superPassoword: string |"",
     banner: string |"",
     fingerType: string |"",
     lastDownloadTime: string |"",
     connectTime: string |"",
     disconnectTime:string |"",
     machineDateTime: string |"",
     temperature: boolean | false,
     serialNumber:string|"",
     softwareVersion: string|"",
     binFileVersion:string|"",
     hardwareVersion:string|"",
     memoryDetail:string|"",
     purgingDays: number|0,
     networkModeTypeID:number | 0,
     autoDateTimeSync: boolean | false,
     printerStatus: boolean | false,
     totalMemory: number | 0,
     freeMemory: number | 0,
     clientHostDetail:string|"",
     romDate:string|"",
     sdkVersion: string |"",
     maxUserLimit :number|0,
     enrolledUser :number |0,
     maxTemplateLimit:number|0,
     enrolledTemplate :number|0,
     matchQualityThreshold :number|0,
     enrollQualityThreshold:number|0,
     matchScoreThreshold:number|0,
     alwaysConnected :boolean | false,
     machinePosition :string | "",
     machineValidity : boolean | false,
     machineActive :boolean | false,
     empType :boolean | false,
     name :boolean | false,
     cardNumber :boolean | false,
     pin :boolean | false,
     finger :boolean | false,
     face :boolean | false,
     snr :boolean | false,
     checkStats:boolean | false,
     dataDownload :boolean | false,
     purging :boolean | false,
     masking :boolean | false,
     addinService :boolean | false,
     machineModelName: string |"",
     machineTypeName: string |""
}
