export interface EmployeeYearlyStatistics{
        groupID: number,
        process: string,
        employeeYearlyStatistics: [
          {
            sequenceNo: number,
            massgaeText: string,
            countNo: string
          }
        ]
    }

export interface SalarySummaryModel{
  employeeID: number,
  monthYearID: number,
  monthYear: string,
  grossRate: number,
  netEaring: number,
  netDeduction: number,
  pf: number,
  esi: number,
  lwf: number,
  pt: number,
  netPay: number
}
export interface MonthlySalaryDetails
  {
    employeeID: number,
    monthYear: string,
    payGroup: string,
    dividingFactor: number,
    paidDays: number,
    arrearDays: number,
    actulaPaidDays: number,
    ctc: number,
    grossRate: number,
    salaryEaring: number,
    salaryDeduction: number,
    salaryPay: number,
    arrearEaring: number,
    arrearDeduction: number,
    arrearPay: number,
    netEaring: number,
    netDeduction: number,
    netPay: number,
    netPayWords: string,
    pf: number,
    vpf: number,
    esi: number,
    pt: number,
    lwf: number,
    pfGross: number,
    vpfGross: number,
    esiGross: number,
    ptGross: number,
    lwfGross: number,
    epsGross: number,
    edliGross: number,
    epfAcc1: number,
    epsAcc10: number,
    pfAdminChargesAcc2: number,
    edliAcc21: number,
    edliAdminChargesAcc22: number,
    esiEmployer: number,
    lwfEmployer: number,
    arrearGrossRate: number,
    arrearPayWord: string,
    arrearPF: number,
    arrearVPF: number,
    arrearESI: number,
    arrearPT: number,
    arrearLWF: number,
    arrearPFGross: number,
    arrearVPFGross: number,
    arrearESIGross: number,
    arrearPTGross: number,
    arrearLWFGross: number,
    arrearEPSGross: number,
    arrearEDLIGross: number,
    arrearEPFAcc1: number,
    arrearEPSAcc10: number,
    arrearPFAdminChargesAcc2: number,
    arrearEDLIAcc21: number,
    arrearEDLIAdminChargesAcc22: number,
    arrearESIEmployer: number,
    arrearLWFEmployer: number,
    arrearShowOnSalarySlip: true,
    paymentMode: string,
    bankBranchID: number,
    bankName: string,
    branchName: string,
    ifscCode: string,
    accountNumber: string,
    remark: string, 
  

}
export interface MonthlySalaryPaidDetails{
      payCode: string,
      payComponentName: string,
      payRate: number,
      payAmount: number,
      arrearAmount: number,
      totalPaidAmount: number,
      payComponentType: string,
      sequenceNumber: number

}
export interface MontylySalaryTotalDetails{
  payRateTotal: number,
  payAmountTotal: number,
  arrearAmountTotal: number,
  paidAmountTotal: number
}
export interface MontylySalaryTotalDetails1{
    payRateTotal: number,
    payAmountTotal: number,
    arrearAmountTotal: number,
    paidAmountTotal: number
}
export interface SalaryDetail {
  monthlySalaryDetails:MonthlySalaryDetails, 
    monthlySalaryPaidDetails: MonthlySalaryPaidDetails[],
  montylySalaryTotalDetails: MontylySalaryTotalDetails,
  montylySalaryTotalDetails1:MontylySalaryTotalDetails1
}
export interface LoanSummaryModel {
  loanDisbursalID: number,
  loanRequestID: number,
  payCode: string,
  loanType: string,
  requestRemark: string,
  loanDisbursalRemark: string,
  numberOfEMI: number,
  principal: number,
  emiStarDate: string,
  loanPayDate: string,
  interestType: string,
  interestRate: number,
  emiAmount: number,
  totalInterestPaid: number,
  totalLoanAmount: number,
  loanStatus: number,
  expectedLoanClosureDate: string,
  approvedDate: string,
  requestDate: string,
  requireDate: string,
  paidAdjustAmount: number,
  paidEMIAmount: number,
  paid: number,
  paidPrincipal: number,
  paidInterest: number,
  unpaidAdjustAmount: number,
  unpaidEMIAmount: number,
  unpaid: number,
  unpaidPrincipal: number,
  unpaidInterest: number,
  adjustmentAmount: number,
  loanSubStatus: number,
  adjustmentAmountOutOfPayrollRestructure: number,
  restructureEMI: number,
  loanCode: string,
  parentLoanDisbursalID: number,
  outstandingBalance: number,
  updatedBy: string,
  updatedDate: string,
  createdBy: string,
  createdDate: string,
  adjustmentDate: string,
  adjustmentBy: string,
  loanEmiDetails: LoanEmiDetails[]
}
export interface LoanEmiDetails {
  loanEMIID: number,
  employeeID: number,
  monthYear: string,
  emiMonth: number,
  emiYear: number,
  payDate: string,
  principal: number,
  interest: number,
  emi: number,
  remainingBalance: number,
  outstandingBalance: number,
  amountToBePaid: number,
  amountDeducted: number,
  outstandingEMI: number,
  interestPenalty: number,
  userAdjuestEMI: number,
  emiAdjustment: string,
  remarks: string,
  processed: number,
  loanType: string,
  adjustmentType: 0
}
export interface LoanRequestModel{
    employeeID: number,
    payCode: string,
    loanAmount: number,
    emi: number,
    requestRemark: string,
    requireDate: string,
    deductFromSalary: boolean,
    deductFromMonthYear: string,
    interestType: string,
    interestRate: number
}

export interface PaidDaysRequest{
  employeePaidDayID: number,
  employeeID: number,
  monthYear: string | null ,
  monthDay: number,
  attendanceCycleStartDate: string | null,
  optimisticDate: string | null,
  attendanceCycleEndDate: string | null,
  dividingFactor: number,
  present: number,
  leave: number,
  absent: number,
  weeklyOff: number,
  holiday: number,
  nationalHoliday: number,
  paidDays: number,
  arrearDays: number,
  actulaPaidDays: number,
  overTimeArrearMinute: string | null,
  workingMinute: string | null,
  overTimeMinute: string | null,
  clLeave: number,
  slLeave: number,
  elLeave: number,
  otherLeave: number,
  lopLeave: number,
  splLeave: number,
  odLeave: number,
  inCount: number,
  outCount: number,
  presentCount: number,
  halfDayCount: number,
  misPunchCount: number,
  srtCount: number,
  lateMinute: string | null,
  lateDays: number,
  earlyMinute: string | null,
  earlyDays: number,
  canteenCount: number,
  canteenAmount: number,
  shiftAllowanceCount: number,
  shiftAllowanceAmount: number,
  attendancePolicyID: number,
  isOptimistic: boolean,
  salaryProcess: boolean,
  dataSource: string | null,
  remark: string | null,
  locked: boolean,
  deductionFlag: string | null,
  lateDeductionDays : number | null,
  lateDeductionValue : number | null
}
export interface LeaveEncashment{
  employeeID: number,
  employeeCode: string,
  employeeName: string,
  company: string,
  department: string,
  designation: string,
  branch: string,
  displayName: string,
  leaveID: number,
  leaveEncashmentDetailID: number,
  accrual: number,
  encashed: number,
  encash: number,
  consume: number,
  balance: number,
  payMonth: string,
  encashAmount: number,
  paid: string,
  leaveCarryForwardDetailID:number,
  carryForward:number,
  lapsLeave:number
}

export interface saveLeaveEncashPayment{
  remark: string,
  paymentEntities: Array<saveLeaveEncashPaymentDt>
}
export interface saveLeaveEncashPaymentDt{
  employeeID: number,
  leaveEncashmentDetailID: number
}

export interface  EmployeeVariableSalary{
  employeeID: number,
  monthYear: string,
  variableSalaries: Array<VariableSalary>
}

export interface VariableSalary{
      payCode: string,
      payComponentName: string,
      amount: 0,
      payAmount: 0,
      formulaApplicable: boolean,
      formula: string | null,
      remarks: string,
      status: boolean
}