export interface salarystructureModel {

}
export interface PayrollEmployee{
    employeeID : number,
    employeeCode: string,
    employeeName: string,
    department: string,
    designation: string,
    branch: string,
    leavingDate: string,
    joiningDate: string,
    employeeStatus: string,
    employeeType: string,
    transactionID: number,
    salaryStructureDetailRequestID: number,
    employeeStatutoryID: number,
}

export interface EmployeeStatutory{
    employeeStatutoryID:number|0,
    employeeID:number,
    pfApplicable:boolean|false,
    vpfApplicable:boolean|false,
    esiApplicable:boolean|false,
    lwfApplicable:boolean|false,
    ptApplicable:boolean|false,
    leaveEncashmentApplicable:boolean|false,
    bonusApplicable:boolean|false,
    gratuityApplicable:boolean|false,
    pensionApplicable:boolean|false,
    pensionNumber:string|"",
    pfGrossLimit:number|0,
    vpfOn:boolean|false,
    vpfAmount:number|0,
    vpfGrossLimit:number|0,
    vpfEffectiveDate:string|null,
    dateOfJoinForm5:string|null,
    dateOfLeavingForm10:string|null,
    npsApplicable:boolean|false,
    npsOn:boolean|false,
    npsPercentage:number|0,
    pfNumber:string|"",
    esiNumber:string|"",
    panNo:string|"",
    aadharNumber:string|"",
    uanNumber:string|"",
    paymentModeID:number|0,
    bankAccountNo:string|"",
    bankName:string|"",
    branchName:string|"",
    ifscCode:string|"",
    paymentBankID:number|0,
    dispensaryID:number|0,
    employeeType:string|""
}

export interface EmployeeSalaryStructure{
    salaryStructureDetailRequestID:number| 0,
    employeeID:number| 0,
    policyID:number| 0,
    ctc:number| 0,
    grossSalary:number| 0,
    netInHandSalary:number| 0,
    employeePF:number| 0,
    employerPF:number| 0,
    employeeESI:number| 0,
    employerESI:number| 0,
    employeeLWF:number| 0,
    employerLWF:number| 0,
    gratuityAmount:number| 0,
    npsAmount:number| 0,
    salaryEffectiveStartDate: string | null,
    salaryEffectiveEndDate:  string | null,
    salaryRevisionDate:  string | null,
    arrearEffectiveDate:  string | null,
    requestStatusID: number| 0,
    requestStatus: string|"",
    approvedDate: string|null,
    requestDate: string|null,
    requestRemark: string|"",
    approveRemark: string|"",
    grossBenefitComponents: Array<SalaryPayComponent>|[],
    recurringDeductionComponents: Array<SalaryPayComponent>|[],
    payComponents: Array<SalaryPayComponent>|[]
}

export interface SalaryPayComponent{
    salaryAnnexureID: number|0,
    employeeID:number|0,
    policyID :number|0,
    payCode:string|"",
    payComponentName: string|"",
    formula:string|"",
    amount:number|0,
    payComponentType:string|""
}