export interface VisitorAdmin
  {
  visitorID: number,
  visitorCode: string | null,
  visitorName: string  | null,
  designationName: string | null,
  contactNumber: string | null,
  companyName: string | null,
  companyAddress: string | null,
  visitTime: string | null,
  visitEndTime: string | null,
  visitStatusID: number,
  profileImagePath: string | null,
  profileImagePathURL: string | null,
  genderID: number,
  visitorTypeID: number,
  visitPurposeID: number,
  employeeID: number,
  employeeDetail: string | null,
  inGateID: number,
  expectedIn: string | null,
  visitorPriorityID: number,
  visitorLogID:number,
  employeeName: string | null,
    employeeDepartment: string | null,
    employeeDesignation: string | null
  }
export interface VisitorInOut{
  visitor: {
    visitorID: number,
    visitorCode: string | null,
    visitorName: string | null,
    genderID: number,
    designationName: string | null,
    emailId: string | null,
    contactNumber: string | null,
    contactNumberVerified: boolean | false,
    idProofID: number,
    idProofNumber: string | null,
    idProofImagePathID:string |null,
    profileImagePathID : string | null,
    idProofImagePath: string | null,
    profileImagePath: string | null,
    companyName: string | null,
    countryID: number,
    stateID: number,
    cityID: number,
    zipCode: number,
    companyAddress: string | null,
    blacklist: true,
    blacklistReason: string | null,
    blacklistDate: string  | null,
    vaccinated: boolean | false,
    noofVaccineDoes: number | 0,
    vaccineCertificateDetali: string | null,
  },
  visitorLogID: number,
  visitorID: number,
  visitorTypeID: number,
  visitPurposeID: number,
  employeeID: number,
  visitorAreaID: number,
  inGateID: number,
  outGateID: number,
  expectedIn: string | null,
  expectedOut: string | null,
  actualIn: string | null,
  actualOut: string | null,
  visitorPriorityID: number,
  visitStatusID: number,
  visitRemarks: string | null,
  bodyTemperature: string | null,
  inRemarks: string | null,
  outRemarks: string | null,
  otherRemarks: string | null,
  vehicleTypeID: number,
  vehicleModel: string | null,
  vehicleNumber: string | null,
  vehicleDetail: string | null,
  requestSourceID: number,
  checkInBy: number,
  checkInByDetail: string | null,
  checkOutBy: number,
  checkOutByDetail: string | null,
  items:Array<VisitorItem> | null,
  otherVisitors:Array<OtherVisitor>
  employeeDetail:string | null,
  employeeName: string | null,
    employeeDepartment: string | null,
    employeeDesignation: string | null
}
export interface OtherVisitor{
    visitorName: string | null,
    genderID: number | 0,
    designationName: string | null,
    contactNumber: string | null,
    remarks: string | null
}

export interface VisitorItem
  {
    visitorItemID: number,
    visitorLogID: number,
    itemTypeID: number,
    brandName: string | null,
    serialNumber: string | null,
    detail: string | null,
    itemScopeID: number,
    remarks: string | null
  }
