export const PATH = {
    AUTH_TOKEN_API:'/Login',
    REFRESH_AUTH_TOKEN_API:'/Login/RefreshAccessToken',
    AUTHENTICATION_API: '/api/authorization/login',
    FORGOT_PASSWORD_VALIDATE_USER:'/forgotpassword/validate/user/',
    FORGOT_PASSWORD_GENERATE_OTP:'/forgotpassword/generate/passowrd/',
    FETCH_BUSINESS_TYPE: '/BusinessType',
    FETCH_COMPANY: '/company',
    FETCH_BRANCH: '/Branch',
    FETCH_CATEGORY: '/Category',
    FETCH_CONTRACTOR: '/Contractor',
    FETCH_DEPARTMENT: '/Department',
    FETCH_DESIGNATION: '/Designation',
    FETCH_CITY: '/City',
    FETCH_QUALIFICATION: '/Qualification',
    FETCH_SUBDEPARTMENT: '/SubDepartment',
    FETCH_SECTION: '/Section',
    FETCH_BANK: '/Bank',
    FETCH_BANKBRANCH: '/BankBranch',
    FETCH_LEVEL: '/Level',
    FETCH_NATUREOFWORK: '/NatureOfWork',
    FETCH_ORGANIZATION: '/Organization',
    FETCH_DISPENSARY:'/Dispensary',
    FETCH_GRADE:'/Grade',
    FETCH_GATE:'/GateMaster',
    FETCH_ITEM_TYPE:'/ItemType',
    FETCH_VISITOR_AREA:'/VisitorArea',
    FETCH_VISITOR_TYPE:'/VisitorType',
    FETCH_VISIT_PURPOSE:'/VisitPurpose',
    FETCH_EMPLOYEE:'/Employee',
    FETCH_EMPLOYEE_MASTER:'/Employee/Master',
    FETCH_AUTO_CODE:'/AutoCodeSeries',
    FETCH_AUTO_CODE_ORG:'/AppData/Organization',
    FETCH_CODE_SERIES_MAP_DATA:'/AutoCodeSeries/{1}/{0}',
    FETCH_USER_GROUP:'/UserGroup',
    FETCH_USER_GROUP_TYPE :'/AppData/UserGroupType',
    UPDATE_MAPPING_ACCESS: '/UserGroup/UserGroupMenuMaping',
    SEARCH_GLOBAL_DATA:'/GlobalSearch/AutoSearch',
    FETCH_EMPLOYEE_DETAIL:'/Employee/{1}',
    FETCH_GLOBAL_SETTING:'/GlobalSetting',
    FETCH_APP_DATA:'/AppData',
    FETCH_USER_MAPPING_MENU:'/UserGroup/UserGroupMenuMaping/',
    FETCH_FILE_VIRTUALPATH:'/File',
    FETCH_DOCUMENT_TYPE:'/DocumentType',
    FETCH_VISITOR_PASS_TEMPLATE:'/VisitorPassTemplate',
    FETCH_VISITOR_ADMIN:'/VisitorAdmin',
    FETCH_VISITOR_ESS:'/VisitorESS',
    FETCH_GLOBAL_EMPLOYEE_FILTER:'/GlobalSearch/EmployeeFilter',
    FETCH_SHIFT_DATA: '/Shift',
    FETCH_SHIFTMAPPING_DATA: '/AttendancePolicy/shiftMapping/',
    FETCH_EMPLOYEE_USERGROUP:'/EmployeeUserGroup/Mapping/',
    UPSERT_EMPLOYEE_USERGROUP:'/EmployeeUserGroup/',
    FETCH_MENU_ITEMS:'/UserGroup/GetMenuItems?id=6',
    FETCH_ATTENDANCE_POLICY_MASTER:'/AttendancePolicy',
    FETCH_EMPLOYEES_OUSTATUS: '/EmployeeUserGroup/OUMapping/',
    FETCH_EMPLOYEE_OU: '/EmployeeUserGroup/UserOUMapping/',
    UPSERT_EMPLOYEE_OUMAPPING: '/EmployeeUserGroup/UserOUMapping/',
    FETCH_LEAVE_DATA: '/leaveMaster',
    FETCH_MAILSERVER:'/MailServer',
    FETCH_SMSSERVER:'/SMSServer',
    FETCH_GENERALSETTINGS:'/VisitorGeneralSetting',
    FETCH_SELF_VISITOR_REQUEST:'/VisitorSelf/VisitRequest',
    SEND_OTP:'/OTPValidation/SendOTP',
    VERIFY_OTP:'/OTPValidation/VerifyOTP',
    FETCH_VISITOR_GENERAL_SETTING :'/VisitorGeneralSetting',
    CHANGE_PASSWORD :'/ResetPassword',
    DOWNLOAD_REPORT:'/VisitorAdmin/DownloadReport',
    RESET_EMP_PASSWORD :'/ResetPassword/ResetEmpPwd/',
    TOGGLE_ESS_ACCESS  :'/Employee/ToggleESSAccess/',
    FETCH_LEAVE_POLICY: '/LeavePolicy',
    FETCH_LEAVECODE_MAPPING: '/LeavePolicy/LeaveCodeMapping/',
    FETCH_LEAVE_OU_MAPPING: '/LeavePolicy/organizatioMapping/',
    FETCH_VISITOR_ADMIN_STATUS:'/VisitorAdmin/VisitStatus/{visitDate}',
    FETCH_HOLIDAY_MASTER:'/TimeOffice/Setting/Holiday/',
    MACHINE_GETALL:'/DC/Machine/GetAll',
    MACHINE_GETBYID:'/DC/Machine/GetByID/',
    MACHINE_CREATE:'/DC/Machine/Create',
    MACHINE_UPDATE:'/DC/Machine/Update',
    MACHINE_DELETE:'/DC/Machine/Delete/',
    GET_MACHINE_MODEL:'/DC/Machine/GetMachineModels',
    GET_MACHINE_TYPE:'/DC/Machine/GetMachineTypes',
    GET_MACHINE_CONNTYPE:'/DC/Machine/GetConnTypes',
    GET_NETWORKMODE_TYPES:'/DC/Machine/GetNetworkModes',
    GET_MACHINEJOB_PROCESS_STATUS: '/DC/MachineJob/GetMachineJobProcessStatus',
    FETCH_HOLIDAY_CALENDER_POLICY:'/TimeOffice/Setting/HolidayCalendar',
    FETCH_REPORT_SETUP:'/report',
    FETCH_USER_ATTENDANCE_DETAIL :'/AttendanceDetail/',
    GENERATE_REPORT:'/Report/generate',    
    GENERATE_SARY_SLIP:'/SelfService/generateSalarySlip/',    
    FETCH_USER_PUNCH_DETAIL :'/AttendanceDetail/Punch',
    SAVE_MANUAL_ATT_PROCESS:'/AttendanceManualProcess/',
    SUBMIT_VERIFICATION_PROCESS:'/AttendanceManualProcess/Verification/',
    SUBMIT_LATE_DEDUCTION_PROCESS:'/AttendanceManualProcess/LateDeduction/',
    // FETCH_WORKFLOW:'/Workflow/',
    // FETCH_WORKFLOW_RULE: '/Workflow/rule/',
    // FETCH_ORG_MAP_WORKFLOW: '/Workflo/w/organizatioMapping/',
    MACHINE_EMP_BIOMETRIC_GETALL: '/DC/EmpBiometricData/GetAll',
    MACHINE_EMP_ENROLL: '/DC/EmpBiometricData/EnrollEmployeeBioToMachine',
    MACHINE_EMP_SEARCH: '/DC/EmpBiometricData/GetRegisteredEmpMachineData',
    MACHINE_UNREGISTER_EMP: '/DC/EmpBiometricData/GetUnRegisteredEmployee',
    GATE_PASS:'/GatePass/Admin',
    FETCH_IMPORT_MASTER:'/Import/masters',
    FETCH_IMPORT_TEMPLATE:'/Import/template/',
    IMPORT_UOLOAD_FILE:'/Import/uploadFile/',
    FETCH_USER_DASHBOARD_SETTING:'/UserGroup/UserGroupDashboardSetting',
    FETCH_EMPLOYEE_DASHBOARD_SETTING:'/UserGroup/GetEmployeeDashboardSetting/',
    UPDATE_EMPLOYEE_DASHBOARD_SETTING:'/UserGroup/UpdateEmployeeDashboardSetting/',
    FETCH_DUMMY_DATA :'/DummyData',
    FETCH_EMPLOYEE_Birthday_Status:'/SelfService/BirthdayList?',
    FETCH_REQUEST_FLOW_DATA:'/SelfService/employeeAllRequest',
    FETCH_REQUEST_APPROVE_DATA:'/SelfService/approverAllRequest',
    FETCH_LEAVE_REQUEST:'/LeaveRequest/',
    FETCH_LEAVE_ACCRUAL:'/LeaveAccrual/',
    FETCH_WORKFLOW_REQUESTDETAIL:'/SelfService/workFlowRequest',
    APPROVE_REQUEST_BY_ESS:'/SelfService/aproveRequest/ess',
    CANCEL_REQUEST_BY_USER:'/SelfService/CancelUndo',
    FETCH_EMPLOYEE_HOLIDAY:'/EmployeeHoliday/Holiday',
    FETCH_EMPLOYEE_ATTENDANCE:'/AttendanceDetail/',
    FETCH_EMPLOYEE_LEAVE:'/LeaveRequest/LeaveBalance/',
    FETCH_EMPLOYEE_ATTENDANCE_STATS:'/AttendanceDetail/DashboardAttendanceStatistics/',
    FETCH_EMPLOYEE_WORKFLOW:'/SelfService/EmployeeWorkflow?',
    SAVE_EMPLOYEE_GATE_PASS:'/GatePass/Employee/',
    GET_PUNCH_REGULARIZATION_DATA:'/PunchRegularization/RequestDetailForESS',
    POST_PUNCH_REGULARIZATION_DATA:'/PunchRegularization/RequestByESS',
    FETCH_EMPLOYEE_ATTENDANCE_STATS_DOWNLOAD:'/AttendanceDetail/DownloadDashboardAttendanceStatistics/',
    DOWNLOAD_POLICY :'/DownloadPolicy/',
    FETCH_FINANCIAL_YEAR:'/FinancialYear?financialYearId=0',
    
    FETCH_ALERT_TAGS:'/AppData/Tag/',
    FETCH_TEMPLATE_TYPE:'/AppData/TemplateType/',
    // OU MApping
    GET_OU_MAPPING:'/OUPolicy/',
    GET_PAYGROUP_ORGANIZATION_MAPPING:'/organizatioMapping/GetPayGroup/',
    UPDATE_PAYGROUP_ORGANIZATION_MAPPING:'/organizatioMapping/UpdatePayGroup/',
    // template Constant
    FETCH_ALERT_TEMPLATE:'/{0}/GetAlertTemplate',
    UPDATE_ALERT_TEMPLATE:'/{0}/UpdateAlertTemplate',
    GET_LETTER_TEMPLATE:'/{0}/GetLetterTemplate',
    SAVE_LETTER_TEMPLATE:'/{0}/SaveLetterTemplate',
    //DELETE_LETTER_TEMPLATE:'/{0}/DeleteLetterTemplate',
    // Workflow Path
    FETCH_WORKFLOW:'/{0}/GetWorkFlow/',
    FETCH_WORKFLOW_RULE: '/{0}/GetWorkflowRule/',
    ADD_WORKFLOW_RULE:'/{0}/AddWorkFlowRule/',
    UPDATE_WORKFLOW_RULE:'/{0}/UpdateWorkFlowRule/',
    DELETE_WORKFLOW_RULE:'/{0}/DeleteWorkFlowRule/',
    GET_WORKFLOW_OU_MAPPING:'/{0}/GetWorkFlowRuleOUMapping/',
    UPDATE_WORKFLOW_OU_MAPPING:'/{0}/UpdateWorkFlowRuleOUMapping/',
    TEAM_DETAIL:'/Team/',
  //OU 
    
    // payroll path constant
    PF_SETTING:'/Payroll/PFSetting',
    ESI_SETTING:'/Payroll/ESISetting',
    LWF_SETTING:'/Payroll/LWFSetting',
    PT_SETTING:'/Payroll/PTSetting',
    WAGES_MASTER:'/Payroll/MinimumWagesMaster',
    GRATUITY_SETTING:'/Payroll/GratuitySetting',
    BONUS_SETTING:'/Payroll/BonusSetting/All',
    ADD_BONUS_SETTING:'/Payroll/BonusSetting/Add',
    UPDATE_BONUS_SETTING:'/Payroll/BonusSetting/Update',
    DELETE_BONUS_SETTING:'/Payroll/BonusSetting/Delete',
    FETCH_PAY_HEADS:'/PayComponent/PayHead',
    FETCH_PAY_HEADS_KEYVALUE:'/PayComponent/PayHeadDDL',
    FETCH_PAY_COMPONENTS:'/PayComponent/payComponent',
    PROCESS_DASHBOARD:'/ProcessDashboard/',
    PROCESS_DASHBOARD_DOWNLOAD:'/DownloadProcessDashboard/',
    SAVE_PAY_COMPONENTS:'/PayComponent/Add',
    UPDATE_PAY_COMPONENTS:'/PayComponent/Update',
    GET_PAY_GROUP:'/OUPolicy/GetPayGroup',
    DELETE_PAY_GROUP:'/OUPolicy/DeletePayGroup/',
    GET_DETAIL_PAY_GROUP:'/PayGroup/Detail',
    SAVE_PAY_GROUP:'/PayGroup/Add',
    UPDATE_PAY_GROUP:'/PayGroup/Update',
    UPDATE_PAY_GROUP_COM_MAPPING:'/PayGroup/PayComponentMapping',
    DELETE_PAY_COMPONENTS:'/PayComponent/Delete',
    DELETE_LETTER_TEMPLATE:'/Payroll/DeleteLetterTemplate',
    GET_PAY_COM_MAPPING_DATA:'/PayGroup/GetPayComponentMapping',
    UPDATE_PAY_COM_MAPPING_DATA:'/PayGroup/UpdatePayComponentMapping',

    //Paid Days
    FETCH_PROCESS_DETAIL:'/PaidDays/',
    //salary structure
    FETCH_PAYROLL_EMPLOYEE_LIST:'/SalaryStructure/GetPayrollEmployee?',
    FETCH_PAYROLL_EMPLOYEE_STATUTORY:'/SalaryStructure/GetStatutoryEmployee?',
    SAVE_EMPLOYEE_STATUTORY:'/SalaryStructure/UpsertEmployeeStatutory',
    FETCH_PAYROLL_EMPLOYEE_SALARYSTRUCTURE:'/SalaryStructure/GetEmployeeSalaryStructure?',
    SAVE_EMPLOYEE_SALARYSTRUCTURE:'/SalaryStructure/InsertEmpSalaryStructure',
    // payroll action 
    GET_EMPLOYEE_YEAR_STATICS:'/EmployeeYearlyStatistics/Payroll?EmployeeID={1}&FinancialYearID={2}',
    GET_SALARY_SUMMARY:'/Salary/summary/{1}/{2}',
    GET_SALARY_SUMMARY_MONTHLY:'/Salary/Summarydetails/{1}/{2}',
    UN_PROCESS_SALARY:'/Salary/UnProcessRequest',
    PROCESS_SALARY:'/Salary/ProcessRequest',
    GET_LOAN_SUMMARY:'/Loan/summary/',
    SALARY_DASHBOARD:'/Salary/',
    GET_EMP_MAPPED_COMPONENT:'/SalaryStructure/EmployeeMappedPayComponent',
    LOAN_REQUEST:'/LoanRequest/',
    GET_EMPLOYEE_VARIABLE_SALARY:'/SalaryStructure/GetEmployeeValiableSalary',
    UPDATE_EMPLOYEE_VARIABLE_SALARY:'/SalaryStructure/UpdateEmployeeValiableSalary',

     // New Changes
     FETCH_SETTLEMENT_REASON:'/Payroll/SettlementReason/All',
     SAVE_SETTLEMENT_REASON:'/Payroll/SettlementReason/Add',
     UPDATE_SETTLEMENT_REASON:'/Payroll/SettlementReason/Update',
     DELETE_SETTLEMENT_REASON:'/Payroll/SettlementReason/Delete',
     FETCH_FINANCIALY_YEAR:'/FinancialYear',
     SAVE_FINANCIALY_YEAR:'/FinancialYear',
     UPDATE_FINANCIALY_YEAR:'/FinancialYear',
     DELETE_FINANCIALY_YEAR:'/FinancialYear',
    //End
    // EncashPayment

    ENCASH_PAYMENT:'/LeaveEncashment/',
    LEAVE_CARRY_FORWORD:'/LeaveCarryForward/',
    SAVE_LOAN_ADJUSTMENT:'/Loan/EmiAdjustment/',

    //separation
    FETCH_EMPLOYEE_SETTLEMENT_LIST:'/settlement/employeelist?',
    FETCH_EMPLOYEE_SEPARATION_DETAIL:'/settlement/employeeSeparationDetail/',
    FETCH_EMPLOYEE_SETTLEMENT_DETAIL:'/settlement/employeeSettlementDetail/',
    SAVE_EMPLOYEE_SEPARATION_DETAIL:'/settlement/updateEmployeeSeparationDetail',
    SAVE_EMPLOYEE_SETTLEMENT_DETAIL:'/settlement/updateEmployeeSettlementDetail',

    //challan
    FETCH_CHALLAN:'/PayrollChallan/GetChallan?',
    FETCH_CHALLAN_DETAIL:'/PayrollChallan/GetChallanDetail?',
    GENERATE_CHALLAN:'/PayrollChallan/GenerateChallan',
    DOWNLOAD_CHALLAN:'/PayrollChallan/DownloadChallan',

    //arrear
    FETCH_EMPLOYEE_ARREAR_LIST:'/Settlement/GetEmployeeArrearList',
    PROCESS_ARREAR_REQUEST:'/Settlement/ProcessArrearRequest',
    FETCH_EMPLOYEE_ARREAR_DETAIL:'/Settlement/GetEmployeeArrearDetail',
    UNPROCESS_ARREAR_REQUEST:'/Settlement/UnProcessArrearRequest',

    //bonus process
    FETCH_EMPLOYEE_LIST_FOR_PROCESS:'/BonusProcess/EmployeeForProcess?',
    FETCH_EMPLOYEE_BONUS_DETAIL:'/BonusProcess/EmployeeBonusDetail',
    PROCESS_BONUS_DATA:'/BonusProcess/Process',
    UNPROCESS_BONUS_DATA:'/BonusProcess/UnProcess',

    //ess request
    FETCH_ADMIN_REQUEST_DATA :'/SelfService/AdminAllRequest/',
    APPROVE_REJECT_ESS_REQUEST_BY_ADMIN :'/SelfService/AproveRequest/Admin',

    // Coff process
    POST_COFF_PROCESS:'/CofManage/Admin/CofProcess',
    GET_COFF_PROCESS:'/CofManage/Admin/GetList',
    POST_Multiple_COFF_PROCESS:'/CofManage/Admin/CofProcessRequest',
    
    // Canteen
    FETCH_ITEM_MASTER:'/CanteenSetup/itemMaster/getAll',
    SAVE_ITEM_MASTER:'/CanteenSetup/itemMaster/create',
    UPDATE_ITEM_MASTER:'/CanteenSetup/itemMaster/update',
    DELETE_ITEM_MASTER:'/CanteenSetup/itemMaster/delete/',

        // Canteen Policy 
        FETCH_CANTEEN_POLICY: '/CanteenSetup/policy/getall',
        FETCH_CANTEEN_OUMAP:'/CanteenSetup/policy/getorganizatioMapping/',
        UPDATE_CANTEEN_OUMAP:'/CanteenSetup/policy/UpdateorganizatioMapping',
        POST_CANTEEN_POLICY:'/CanteenSetup/policy/create',
        UPDATE_CANTEEN_POLICY:'/CanteenSetup/policy/update',
        DELETE_CANTEEN_POLICY:'/CanteenSetup/policy/Delete',
        FETCH_CANTEEN_POLICY_ID: '/CanteenSetup/policy/',
     // canteen process 
        POST_CANTEEN_MANAUL_PUNCH:'/CanteenUser/Manula/Punch',
        POST_CANTEEN_PROCESS_SINGLE:'/CanteenUser/CanteenProcess/Single', 
        POST_CANTEEN_PROCESS_MULTIPLE:'/CanteenUser/CanteenProcess/Muliple', 
        FETCH_CANTEEN_PUNCHDETAILS:'/CanteenUser/PunchDetail/getAll',
      // Other punch
        SAVE_REQUESTBYESS:'/OtherPunch/RequestByESS',
        UPDATE_EMPLOYEEGEOLOCATION:'/EmployeeUserGroup/UpdateEmployeeGeoLocation',
  }
